public class Calc {
    public static void Multiplication(int num1, int num2){
        int num = num1 * num2;
        System.out.println("The answer is " + num);
    }
    public static void Division(int num1, int num2) {
        int num = num1 / num2;
        System.out.println("The answer is " + num);
    }
    public static void Addition(int num1, int num2) {
        int num = num1 + num2;
        System.out.println("The answer is " + num);
    }
    public static void Subtraction(int num1, int num2) {
        int num = num1 - num2;
        System.out.println("The answer is " + num);
    }
}
